// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using e_shop_Qingyuan_zeng_s316740.Data;

namespace e_shop_Qingyuan_zeng_s316740.Migrations
{
    [DbContext(typeof(eShopDBContext))]
    [Migration("20200911012146_modelsUpdate01")]
    partial class modelsUpdate01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("e_shop_Qingyuan_zeng_s316740.Models.item", b =>
                {
                    b.Property<int>("itemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("itemImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("itemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("itemPrice")
                        .HasColumnType("int");

                    b.Property<string>("itemType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("shoppingCartId")
                        .HasColumnType("int");

                    b.Property<string>("userEmail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("itemId");

                    b.HasIndex("shoppingCartId");

                    b.ToTable("items");
                });

            modelBuilder.Entity("e_shop_Qingyuan_zeng_s316740.Models.shoppingCart", b =>
                {
                    b.Property<int>("shoppingCartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("userEmail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("shoppingCartId");

                    b.ToTable("shoppingCarts");
                });

            modelBuilder.Entity("e_shop_Qingyuan_zeng_s316740.Models.item", b =>
                {
                    b.HasOne("e_shop_Qingyuan_zeng_s316740.Models.shoppingCart", null)
                        .WithMany("items")
                        .HasForeignKey("shoppingCartId");
                });
#pragma warning restore 612, 618
        }
    }
}
